version: '2.4'
services:
  mysql:
    image: mysql:8.0.33
    environment: 
      MYSQL_DATABASE:      y34rz3r0
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_USER:          y34rz3r0
      MYSQL_PASSWORD:      1234
    volumes:
    - type: bind
      source: ../config/my.cnf
      target:   /etc/mysql/my.cnf
      read_only: true
    - type: bind
      source: /Volumes/mysql_dump
      target: /mnt/mysql_dump
